export const INIT = "INIT";
export const DATA_DID_NOT_LOAD = "DATA_DID_NOT_LOAD";
export const SET_LOADING = "SET_LOADING";
export const SET_CONFIG = "SET_CONFIG";

// date 
export const SET_NOW_TIME = "SET_NOW_TIME";
export const SET_NOW_DATE = "SET_NOW_DATE";
export const SET_CALENDAR_DATE = "SET_CALENDAR_DATE";
export const SET_DATE_CONFIG = "SET_DATE_CONFIG";
export const INCREASE_CALENDAR_DATE = "INCREASE_CALENDAR_DATE";
export const DECREASE_CALENDAR_DATE = "DECREASE_CALENDAR_DATE";

export const TOGGLE_CALENDAR = "TOGGLE_CALENDAR";
export const CHANGE_SELECTED_DATE = "CHANGE_SELECTED_DATE";
export const CHANGE_CALENDAR_DATE = "CHANGE_CALENDAR_DATE";
export const UPDATE_NOW_DATE = "UPDATE_NOW_DATE";
export const UPDATE_PARK_STRING_DATE = "UPDATE_PARK_STRING_DATE";
export const UPDATE_PARK_STRING_TIME = "UPDATE_PARK_STRING_TIME";

// other modules
export const CHANGE_SELECTED_WINCH = "CHANGE_SELECTED_WINCH";
export const CHANGE_SELECTED_TEACHER = "CHANGE_SELECTED_TEACHER";
export const CHANGE_SELECTED_TIME = "CHANGE_SELECTED_TIME";
export const CLEAR_SELECTED_TIME = "CLEAR_SELECTED_TIME";

// alert
export const RES_SEND_ALERT = "RES_SEND_ALERT";
export const RES_CLEAR_ALERT = "RES_CLEAR_ALERT";

// buffer
export const PUSH_TO_BUFFER_TEACHER_TURN = "PUSH_TO_BUFFER_TEACHER_TURN";
export const PUSH_TO_BUFFER_WINCH_TURN = "PUSH_TO_BUFFER_WINCH_TURN";
export const DELETE_TIME_FROM_BUFFER_WINCH_TURN = "DELETE_TIME_FROM_BUFFER_WINCH_TURN";
export const DELETE_TIME_FROM_BUFFER_TEACHER_TURN = "DELETE_TIME_FROM_BUFFER_TEACHER_TURN";
// buffer midellware
export const DELETE_ITEM_TIME_FROM_BUFFER = "DELETE_ITEM_TIME_FROM_BUFFER";
export const SET_SELECTED_DATA_TO_BUFFER = "SET_SELECTED_DATA_TO_BUFFER";

export const GET_WINCH_DATE_TURN = "GET_WINCH_DATE_TURN";
export const GET_TEACHER_DATE_TURN = "GET_TEACHER_DATE_TURN";

// form
export const SET_FORM_STATE = "SET_FORM_STATE";
export const TOGGLE_FORM_IS_SHOW = "TOGGLE_FORM_IS_SHOW";
export const SET_DELAY_SEND_NEXT_SMS = "SET_DELAY_SEND_NEXT_SMS";
export const CHANGE_INPUT_CODE_VALUE = "CHANGE_INPUT_CODE_VALUE";
export const CHANGE_INPUT_NAME_VALUE = "CHANGE_INPUT_NAME_VALUE";
export const CHANGE_INPUT_PHONE_VALUE = "CHANGE_INPUT_PHONE_VALUE";
export const CHANGE_INPUT_PASSWORD_VALUE = "CHANGE_INPUT_PASSWORD_VALUE";
export const CHANGE_INPUT_REPEAT_PASSWORD_VALUE = "CHANGE_INPUT_REPEAT_PASSWORD_VALUE";

// client
export const SET_CLIENT = "SET_CLIENT";
export const SET_ITEM_TO_RESERVATION_LIST = "SET_ITEM_TO_RESERVATION_LIST";
export const DELETE_ITEM_FROM_RESERVATION_LIST = "DELETE_ITEM_FROM_RESERVATION_LIST";

export const UPDATE_CLIENT_RESERVATION = "UPDATE_CLIENT_RESERVATION";
export const SET_CLIENT_RESERVATION = "SET_CLIENT_RESERVATION";

// clinet_nav 
export const TOGGLE_SHOW_CLIENT_NAV = "TOGGLE_SHOW_CLIENT_NAV";
export const TOGGLE_SHOWED_DATE = "TOGGLE_SHOWED_DATE";
export const CLOSSE_SHOWED_DATE = "CLOSSE_SHOWED_DATE";
export const SET_RECENTLY_SAVED = "SET_RECENTLY_SAVED";

// fetch
export const CHECK_PHONE_NUMBER = "CHECK_PHONE_NUMBER";
export const SIGN_UP = "SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const UPDATE_CLIENT_DATA = "UPDATE_CLIENT_DATA";
export const RETRIVEE_PASSWORD = "RETRIVEE_PASSWORD";
export const SET_RESERVATION_TIME = "SET_RESERVATION_TIME";
export const DELETE_RESERVATION_TIME_ITEM = "DELETE_RESERVATION_TIME_ITEM";
