export const SET_DURATION_OF_SET = "SET_DURATION_OF_SET";
export const SET_OPEN_WORK_TIME = "SET_OPEN_WORK_TIME";
export const SET_CLOSSE_WORK_TIME = "SET_CLOSSE_WORK_TIME";
export const SET_SHOW_ICONS_RESERVED = "SET_SHOW_ICONS_RESERVED";

// winches
export const SET_WINCH_DATA = "SET_WINCH_DATA";
export const ADD_WINCH = "ADD_WINCH";
export const REMOVE_WINCH = "REMOVE_WINCH";

// admins 
export const GET_CLIENT_FOR_ADMIN = "GET_CLIENT_FOR_ADMIN";
export const ADD_ADMIN = "ADD_ADMIN";
export const SET_ADMIN_RIGHTS = "SET_ADMIN_RIGHTS";
export const REMOVE_ADMIN = "REMOVE_ADMIN";