export const SET_LOG_IN_FORM_STATE = "SET_LOG_IN_FORM_STATE";
export const RECAPTCHA_ON_LOADED = "RECAPTCHA_ON_LOADED";
export const RECAPTCHA_ON_VERIFY = "RECAPTCHA_ON_VERIFY";

export const SET_DELAY_SENDING_REPEATED_SMS = "SET_DELAY_SENDING_REPEATED_SMS";